import Image from 'next/image';
import Link from 'next/link';

import Select from '@/components/Select';
import Tooltip from '@/components/Tooltip';
import { CurrencyVaultIcon, InformationIcon, TVaultIcon, VaultIcon } from '@/components/icons';

import logoImg from '../../../public/images/logo.png';

export default function LaunchApp() {
  return (
    <>
      <nav className="w-full flex flex-wrap items-center justify-between py-8">
        <Link href="/" className="flex items-center space-x-3 rtl:space-x-reverse">
          <Image
            src={logoImg}
            alt="Rock Onyx Logo"
            width={28}
            height={36}
            className="w-auto h-full"
          />
          <p className="text-3xl uppercase">Rock Onyx</p>
        </Link>
        <ul className="flex items-center gap-12">
          <li className="text-base font-light uppercase cursor-pointer hover:font-medium">
            Product
          </li>
          <li className="text-base font-light uppercase opacity-30 cursor-pointer hover:font-medium">
            Portfolio
          </li>
        </ul>
        <button
          type="button"
          className="text-sm text-white uppercase bg-white bg-opacity-10 rounded-3xl px-6 py-3 text-center hover:ring-2 hover:ring-gray-800"
        >
          Connect wallet
        </button>
      </nav>
      <div
        className="w-full h-[1px]"
        style={{
          background:
            'linear-gradient(270deg, rgba(50, 40, 163, 0.00) -4.13%, rgba(107, 107, 107, 0.76) 49.02%, rgba(50, 40, 163, 0.00) 100%)',
        }}
      />

      <div className="flex gap-6 w-fit mt-12 mx-auto">
        <div className="w-40">
          <Select
            placeholder="Strategy"
            options={[
              { label: 'Strategy 1', value: 'Strategy 1' },
              { label: 'Strategy 2', value: 'Strategy 2' },
              { label: 'Strategy 3', value: 'Strategy 3' },
            ]}
          />
        </div>
        <div className="w-48">
          <Select
            placeholder="Deposit asset"
            options={[
              { label: 'Deposit asset 1', value: 'Deposit asset 1' },
              { label: 'Deposit asset 2', value: 'Deposit asset 2' },
              { label: 'Deposit asset 3', value: 'Deposit asset 3' },
            ]}
          />
        </div>
        <div className="w-36">
          <Select
            placeholder="Sort by"
            options={[
              { label: 'Ascending', value: 'asc' },
              { label: 'Descending', value: 'desc' },
            ]}
          />
        </div>
      </div>

      <Link href="/stable-coin-vault" className="grid grid-cols-3 w-4/5 mx-auto mt-32 mb-60">
        <div className="bg-rock-bg-tab rounded-2xl">
          <div className="relative bg-rock-secondary bg-opacity-10 p-6 pb-14">
            <div className="flex items-center gap-2">
              <p className="w-fit bg-rock-blue bg-opacity-40 rounded-lg px-4 py-2 uppercase">
                Stable Coin Vault
              </p>
              <span className="bg-rock-blue bg-opacity-40 rounded-lg px-2.5 py-2">
                <VaultIcon />
              </span>
            </div>
            <div className="flex items-center gap-1 absolute -bottom-9">
              <TVaultIcon />
              <CurrencyVaultIcon />
            </div>
          </div>

          <div className="flex flex-col gap-6 px-6 pt-16 pb-6">
            <p className=" text-3xl font-semibold uppercase">Stable Coin Vault</p>

            <div>
              <div className="flex items-center gap-2">
                <p className="text-sm font-semibold text-rock-gray">Total Projected Yield (APY)</p>
                {/* <Tooltip
                  message={
                    <div>
                      <div className="grid grid-cols-2 gap-y-2 text-xs text-rock-gray">
                        <p className="text-rock-highlight">
                          Total Projected Yield (APY)
                        </p>
                        <p className="text-rock-highlight justify-self-end">
                          0.140000 00%
                        </p>
                        <p>abc</p>
                        <p className="justify-self-end">0.140000 00%</p>
                        <p>abc</p>
                        <p className="justify-self-end">0.140000 00%</p>
                      </div>
                      <p className="text-xs font-normal break-words mt-2">
                        Vault yield is calculated by annualizing the 4-week
                        average weekly yield generated by the vault. The weekly
                        yield does not include any losses incurred by the vault
                      </p>
                    </div>
                  }
                > */}
                <InformationIcon />
                {/* </Tooltip> */}
              </div>
              <p className="text-2xl font-semibold">392%</p>
            </div>

            <div>
              <p className="text-sm font-semibold text-rock-gray">Total value locked TVL</p>
              <p className="text-2xl font-semibold">$7,945</p>
            </div>

            <div className="flex flex-col gap-2 mt-8">
              <div className="w-full h-1 bg-rock-button rounded-full">
                <div className="h-1 bg-white rounded-full" style={{ width: '0.2%' }}></div>
              </div>
              <div className="flex items-center justify-between text-sm text-caption">
                <p className="text-rock-gray">Max Capacity</p>
                <p>4M</p>
              </div>
            </div>
          </div>
        </div>
      </Link>

      <div className="absolute top-[56%] 2xl:top-[40%] w-full h-[100vh] opacity-60 blur-[60px] overflow-y-hidden">
        <div
          className="w-full h-full absolute top-full left-1/2 -translate-x-1/2 rounded-full mix-blend-difference blur-[290px] rotate-[-15deg]"
          style={{
            background: 'linear-gradient(243deg, #D3382C 30.36%, #001AFF 70.7%)',
          }}
        />
      </div>
    </>
  );
}
