'use client';

import { useMemo } from 'react';

import { Card, Tooltip } from '@nextui-org/react';
import Link from 'next/link';

import { Address } from '@/@types/common';
import { Strategy, VaultNetwork } from '@/@types/enum';
import { Point } from '@/@types/vault';
import { useChainContext } from '@/app/_providers/ChainProvider';
import { NA_STRING } from '@/constants/common';
import useContractMapping from '@/hooks/useContractMapping';
import useVaultQueries from '@/hooks/useVaultQueries';
import { vaultCardMapping } from '@/services/vaultMapping';
import { toCompactNumber, toFixedNumber, withCommas } from '@/utils/number';

import {
  ArbitrumIcon,
  EigenLayerIcon,
  EthereumIcon,
  InformationIcon,
  RenzoIcon,
  UsdcAssetIcon,
  ZircuitIcon,
} from '../shared/icons';

type VaultCardProps = {
  slug: string;
  name: string;
  link?: string;
  apy?: number;
  maxCapacity?: number;
  available?: boolean;
  points?: Point[];
  strategy: Strategy;
  contractAddress: Address;
  network: VaultNetwork;
};

const MAX_CAPACITY = 50 * 1000;

const VaultCard = (props: VaultCardProps) => {
  const {
    name,
    link = '#',
    apy = 0,
    maxCapacity,
    available = true,
    points,
    strategy,
    contractAddress,
    network,
  } = props;

  const { selectedChain } = useChainContext();

  const contracts = useContractMapping();

  const { color, vaultAbi } = vaultCardMapping(name, contracts);

  const { isLoadingTotalValueLocked, totalValueLocked } = useVaultQueries(
    vaultAbi,
    contractAddress,
  );

  const displayedStrategy = useMemo(() => {
    if (strategy === Strategy.OptionsWheel) {
      return 'Options Wheel';
    }

    return 'Delta Neutral';
  }, [strategy]);

  return (
    <Card>
      <Link href={link} className="flex flex-col gap-6 p-8 text-primary">
        <div className="flex items-center justify-between bg-rock-grey01 px-6 py-4 rounded-2xl">
          <div>
            <p className="text-xl font-bold capitalize">{name}</p>
            <div className="flex items-center gap-2">
              {network === VaultNetwork.ArbitrumOne ? (
                <ArbitrumIcon className="w-5 h-5" />
              ) : (
                <EthereumIcon className="w-5 h-5" />
              )}
              <p className="text-sm capitalize">{displayedStrategy}</p>
            </div>
          </div>
          <UsdcAssetIcon className="w-10 h-10" />
        </div>

        <p className="text-sm font-light">
          At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium
          voluptatum deleniti atque corrupti quos dolores.
        </p>

        <div
          className={`grid ${points && points.length > 0 ? 'grid-cols-2' : 'grid-cols-1'} gap-6`}
        >
          <div className="flex flex-col gap-2 items-center bg-rock-grey01 p-4 rounded-2xl">
            <div className="flex items-center gap-2">
              <p className="text-sm opacity-60">APY</p>
              <Tooltip
                showArrow
                color="foreground"
                closeDelay={100}
                classNames={{ base: 'w-64' }}
                content={
                  <div className="p-2">
                    <div className="flex justify-between text-sm text-primary">
                      <p className="text-rock-light-blue">APY</p>
                      <p className="text-rock-light-blue justify-self-end">{`${withCommas(
                        toFixedNumber(apy),
                      )}%`}</p>
                    </div>
                    <p className="text-sm font-normal break-words mt-2">
                      Vault yield is calculated by annualizing monthly yield generated by the vault.
                      The monthly yield does not include any losses incurred by the vault
                    </p>
                  </div>
                }
              >
                <span>
                  <InformationIcon className="block w-4 h-4" />
                </span>
              </Tooltip>
            </div>
            <p className="text-lg font-semibold">{`${withCommas(toFixedNumber(apy))}%`}</p>
          </div>

          <div className="flex flex-col gap-2 items-center bg-rock-grey01 p-4 rounded-2xl">
            <p className="text-sm opacity-60">TVL</p>
            <p className="text-lg font-semibold">
              {totalValueLocked.toLocaleString('en-US', {
                style: 'currency',
                currency: 'USD',
                maximumFractionDigits: 0,
              })}
            </p>
          </div>
        </div>

        {points && points.length > 0 && (
          <div className="bg-rock-grey01 p-4 rounded-2xl">
            <div className="flex items-center justify-around gap-6">
              {points.map((x) => {
                const { label, icon: Icon } =
                  x.name === 'renzo'
                    ? { label: 'Renzo pts', icon: RenzoIcon }
                    : x.name === 'eigenlayer'
                      ? { label: 'EigenLayer pts', icon: EigenLayerIcon }
                      : { label: 'Zircuit pts', icon: ZircuitIcon };

                return (
                  <div key={x.name} className="flex flex-col items-center gap-1">
                    <div className="flex items-center gap-1">
                      <Icon className="w-5 h-5" />
                      <span className="text-sm opacity-60">{label}</span>
                    </div>
                    <p className="font-semibold">
                      {x.point ? withCommas(toFixedNumber(x.point, 1)) : 'Variable'}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <div className="flex flex-col gap-2">
          <div className="flex items-center justify-between text-sm text-caption">
            <p>Max Capacity</p>
            <p>{MAX_CAPACITY ? toCompactNumber(MAX_CAPACITY) : NA_STRING}</p>
          </div>
          <div className="w-full h-1.5 bg-gray-300 rounded-full">
            <div
              className="h-1.5 bg-primary rounded-full"
              style={{ width: `${MAX_CAPACITY ? (totalValueLocked * 100) / MAX_CAPACITY : 0}%` }}
            ></div>
          </div>
        </div>
      </Link>
    </Card>
  );
};

export default VaultCard;
