import Typography from '@/components/shared/Typography';

const DeltaNeutralOverview = () => {
  return (
    <>
      <div className="flex flex-col gap-6">
        <Typography variant="body">
          Generating yield by shorting ETH on a perp markets with a favorable funding rate, while
          holding ETH in spot or yield to be neutral delta against USD
        </Typography>

        <ul className="grid grid-cols-2 gap-6">
          <li className="flex flex-col items-center gap-3 bg-white bg-opacity-5 border border-rock-divider rounded-xl p-6">
            <p className="text-rock-sub-body font-light">ETH Holding</p>
            <p className="text-white text-2xl font-semibold">50%</p>
          </li>
          <li className="flex flex-col items-center gap-3 bg-white bg-opacity-5 border border-rock-divider rounded-xl p-6">
            <p className="text-rock-sub-body font-light">ETH Perp</p>
            <p className="text-white text-2xl font-semibold">50%</p>
          </li>
        </ul>
      </div>

      <div className="flex flex-col gap-8 border border-rock-divider rounded-2xl sm:rounded-3xl p-6 sm:p-8 mt-8">
        <div>
          <p className="uppercase mb-2">
            <span className="inline-block w-2 h-2 bg-white rounded-full mr-2 -translate-y-0.5" />
            Vault receives deposits
          </p>
          <Typography variant="subbody">
            The vault accepts USDC deposits from investors and allocates 60% to a WETH/wstETH
            liquidity position, 20% to a USDC/USDC.e liquidity position (reserve for Option Wheel
            Strategy Model), and 20% to collateral aeUSD in AEVO for bi-weekly options trading.
          </Typography>
        </div>

        <div>
          <p className="uppercase mb-2">
            <span className="inline-block w-2 h-2 bg-white rounded-full mr-2 -translate-y-0.5" />
            ALGORITHMIC STRIKE SELECTION
          </p>
          <Typography variant="subbody">
            We have developed an algorithm to optimally select out-of-the-money (OTM) strikes,
            minimizing the risk of in-the-money (ITM) outcomes in highly volatile markets.
          </Typography>
        </div>

        <div>
          <p className="uppercase mb-2">
            <span className="inline-block w-2 h-2 bg-white rounded-full mr-2 -translate-y-0.5" />
            ALGORITHMIC LP PRICE RANGE SELECTION
          </p>
          <Typography variant="subbody">
            Our algorithm is designed to estimate market volatility and employ statistical methods
            to determine the optimal price range when adding LP positions.
          </Typography>
        </div>

        <div>
          <p className="uppercase mb-2">
            <span className="inline-block w-2 h-2 bg-white rounded-full mr-2 -translate-y-0.5" />
            VAULT OPTIONS
          </p>
          <Typography variant="subbody">
            Every week, the vault generates bi-weekly covered calls/puts options positions based on
            the output of our algorithm, with position sizes ranging from 7% to 10% of the total
            Ether spot holdings.
          </Typography>
        </div>

        <div>
          <p className="uppercase mb-2">
            <span className="inline-block w-2 h-2 bg-white rounded-full mr-2 -translate-y-0.5" />
            VAULT COLLECTS YIELDS
          </p>
          <Typography variant="subbody">
            Every Friday, the vault collects rewards from LP positions and options premiums,
            reinvesting them to represent the yield generated by this strategy.
          </Typography>
        </div>
      </div>
    </>
  );
};

export default DeltaNeutralOverview;
