import { Suspense } from 'react';

import type { Metadata } from 'next';

import '@rainbow-me/rainbowkit/styles.css';
import { Sora } from 'next/font/google';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';

import Footer from '@/components/shared/Footer';
import { config } from '@/config';
import { ContextProvider } from '@/context';

import Providers from './_providers/Providers';
import './globals.css';
import Loading from './loading';

const sora = Sora({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Rock Onyx',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));

  return (
    <html lang="en" className={`${sora.className} bg-rock-bg`}>
      <body className="font-inconsolata">
        <Providers>
          <Suspense fallback={<Loading />}>
            <main className="relative max-w-[90%] mx-auto pb-4">
              <div>{children}</div>
              <Footer />
            </main>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
