export { default as TextWidget } from './TextWidget';
export { default as PieChartWidget } from './PieChartWidget';
export { default as VaultWidget } from './VaultWidget';
export { default as BalanceWidget } from './BalanceWidget';
export { default as FeeWidget } from './FeeWidget';
export { default as StatisticWidget } from './StatisticWidget';
export { default as AreaChartWidget } from './AreaChartWidget';
export { default as DashboardsTemplate } from './DashboardsTemplate';
export { default as VaultDashboardTemplate } from './VaultDashboardTemplate';
