name: Deploy Harmonix App with SST

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-sst-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set STAGE variable
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then 
            echo "STAGE=mainnet" >> $GITHUB_ENV
          else 
            echo "STAGE=testnet" >> $GITHUB_ENV
          fi

      - name: Install SST CLI
        run: curl -fsSL https://ion.sst.dev/install | bash

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Modify this based on your deployment region

      - name: Create .env file
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then 
            NEXT_PUBLIC_APP_ENV='production'
          else 
            NEXT_PUBLIC_APP_ENV='development'
          fi
          echo "NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV" >> .env

          echo "NEXT_PUBLIC_GOOGLE_ANALYTICS=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}" >> .env
          echo "NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}" >> .env
          echo "NEXT_PUBLIC_W3C_PROJECT_ID=${{ secrets.NEXT_PUBLIC_W3C_PROJECT_ID }}" >> .env

          PARAM_PATH="/harmonix-app/$STAGE/"
          params=$(aws ssm get-parameters-by-path --path $PARAM_PATH --with-decryption --query "Parameters[*].{Name:Name,Value:Value}")
          for row in $(echo "${params}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            param_name=$(_jq '.Name' | sed 's|^'"$PARAM_PATH"'||')
            param_value=$(_jq '.Value')
            echo "${param_name}=${param_value}" >> .env
          done

      - name: Set SST Secret
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            DOMAIN_CERT=${{ secrets.MAINNET_DOMAIN_CERT }}
          else
            DOMAIN_CERT=${{ secrets.TESTNET_DOMAIN_CERT }}
          fi
          sst secret set DomainCert $DOMAIN_CERT --stage=$STAGE

      - name: Deploy with SST
        run: sst deploy --stage=$STAGE
